Se agrego el header, elboton del carro y el llamado a la API que trae…
julianfalquez/proyecto-react pull request #1
Opened 2022-02-02 22:03 UTC by julianfalquez

Se agrego el header, elboton del carro y el llamado a la API que traera los productos

2022-02-03 15:52 UTC, luribeto requested changes

2022-02-03 15:52 UTC, luribeto commented on src/components/ProductList/ProductList.js
> +  async function getItems() {
Great Job @julianfalquez !
Can we move this fetch to a service layer folder?
Let's create a new folder for services so we can consume it here for now and then we can move it to a redux flow

2022-02-03 15:52 UTC, luribeto commented on src/components/Header/Header.js
> +        <div>
Question... Do you think is there a way to avoid this intermediate <div> and achieve the same layout result just with one parent div and the img and h1 as their childrens?

2022-02-03 15:52 UTC, luribeto commented on src/components/Cart/CartButton.js
> +      <IconButton color="primary" aria-label="shopping_cart" size="large" onClick={()=>{addOne()}} >
Another question... Can you please give me an idea on how we can connect this same addOne callback functionality to  the ADD PRODUCT button onClick in the lower part of the SEARCHABLE PRODUCTS TABLE ??
If so, can you please give here a brief description of your idea?

2022-02-03 17:44 UTC, julianfalquez commented on src/components/Cart/CartButton.js
> +      <IconButton color="primary" aria-label="shopping_cart" size="large" onClick={()=>{addOne()}} >
Sure, a good way to accomplish this is by using context. I'll create a context for the cart and use it to give other components acces to the addOne function and the Cart product count.

2022-02-03 17:50 UTC, julianfalquez commented on src/components/Header/Header.js
> +        <div>
I'm having some trouble with this one. The reason I added a div there is that I'm trying to create 2 blocks, one for the logo and title and the other one for the Cart button component. I think I may be able to this without a div by creating a new component for the logo and title.

2022-02-03 17:51 UTC, julianfalquez commented on src/components/ProductList/ProductList.js
> +  async function getItems() {
Sure, i'll create a new folder fot the http and item services.

2022-02-03 20:42 UTC, luribeto commented on src/components/Header/Header.js
> +        <div>
Please take a look at the attached js and css snippets for that part, and you can check how we can achieve the same layout result without the use of that extra DIV and less CSS attributes.
<img width="464" alt="Screen Shot 2022-02-03 at 3 38 27 PM" src="https://user-images.githubusercontent.com/14980040/152425200-bc7a98d8-9855-401f-b64a-0eaa97a423ad.png">
<img width="633" alt="Screen Shot 2022-02-03 at 3 40 53 PM" src="https://user-images.githubusercontent.com/14980040/152425207-49cfcee6-98c6-4f44-9f74-e7d904b2ae61.png">

Please take some time looking at the logic behind this markup and styles and please update your component

2022-02-03 20:44 UTC, luribeto commented on src/components/Cart/CartButton.js
> +      <IconButton color="primary" aria-label="shopping_cart" size="large" onClick={()=>{addOne()}} >
OK that sound great in terms if Global State Management, even more for this basic WebApp that we're building. But can you please describe here why did you choose Context API to achieve this new requested feature?

2022-02-03 21:10 UTC, julianfalquez commented on src/components/Header/Header.js
> +        <div>
Oh, ok, I see it now.  I thought you were talking about removing the second div and keeping the one with the header_container class. That's what confused me.

2022-02-03 21:18 UTC, julianfalquez commented on src/components/Cart/CartButton.js
> +      <IconButton color="primary" aria-label="shopping_cart" size="large" onClick={()=>{addOne()}} >
I chose the Context API because it helps with managing state between multiple components. To accomplish the same result without a state manager, well have to create a prop chain that can end up becoming difficult to work with. And I picked it over Redux due to the App being simple enough that the Context API drawbacks won't affect performance.

2022-02-04 12:40 UTC, luribeto commented on src/components/Cart/CartButton.js
> +      <IconButton color="primary" aria-label="shopping_cart" size="large" onClick={()=>{addOne()}} >
Awesome, so please merge this PR and create a new one for the Context implementation where the user can click the ADD PRODUCT and increase the header counter for now.
Later on we're going to add Redux just for study purposes for bigger apps, but let do that with Context API for now.
Great Job on this first PR

2022-02-04 12:41 UTC, luribeto approved these changes

2022-02-04 14:54 UTC, merged